import clsx from "clsx";
import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "../assets/scss/globals.scss";
import "../assets/scss/header.scss";
import AOSComponent from "@/components/AOSComponent";
import Footer from "../components/footer";

export const metadata: Metadata = {
  title: "Project 1",
  description: "Generated by create next app",
};

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(notoSansJP.className)}>
        <AOSComponent>
         {/* <Header/> */}
         {children}
         <Footer/>
        </AOSComponent>
      </body>
    </html>
  );
}
