// import clsx from "clsx";
import type { Metadata } from "next";
import { Roboto_Condensed , Oswald, Inter} from "next/font/google";
import "../assets/scss/globals.scss";
import AOSComponent from "@/components/AOSComponent";
import Footer from "../components/footer";
import Header from "@/components/header";
import { ConfigProvider } from "antd";
import { twMerge } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Project 1",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})
const roboto = Roboto_Condensed({
  subsets: ["latin"],
  variable: "--font-roboto",
});

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(roboto.variable,oswald.variable,inter.variable, "font-roboto bg-[#1B1C1F]")}  suppressHydrationWarning={true}>
        <AOSComponent>
          <ConfigProvider
            theme={{
              components: {
                Select: {
                  activeBorderColor: "#CCC",
                  hoverBorderColor: "#CCC",
                  activeOutlineColor: "transparent",
                  optionFontSize: 20,
                  optionPadding: "20px 8px 20px 8px",
                  selectorBg: "#FFF",
                  showArrowPaddingInlineEnd: 50,
                  
                },
                Input: {
                  activeBorderColor: "#CCC",
                  hoverBorderColor: "#CCC",
                  activeShadow: "transparent",
                  activeBg: "#FFF",
                  addonBg: "#FFF",
                  hoverBg: "#FFF",
                  inputFontSize: 16,
                },
                Form: {
                  itemMarginBottom: 0,
                },
                Modal: {
                  contentBg: "#FFF",
                },
              },
            }}
          >
            <Header />
            <div className="w-full  overflow-hidden">
              {children}
            </div>
            <Footer />
          </ConfigProvider>
        </AOSComponent>
      </body>
    </html>
  );
}
